#spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
#spring.datasource.url=jdbc:mysql://localhost:3306/nCov?serverTimezone=UTC&characterEncoding=utf8
#spring.datasource.username=root
#spring.datasource.password=root
#mybatis.config-location=classpath:/mybatis-config.xml

#server.port=8081


#thymeleaf start
#spring.thymeleaf.mode=HTML
#spring.thymeleaf.encoding=UTF-8
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.content-type=text/html

#spring.thymeleaf.suffix=.html
#spring.thymeleaf.cache=false
#thymeleaf end

#mybatis config
spring:
  profiles:
    active: prod